[[card]]
id = "IMT-01-001"
name = "アテンダントツアラー"
idol = "天海 春香"
rarity = "SSR"
text = "これが私たちみんなで届ける最高のライブなんですっ♪"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1373
dance = 1226
visual = 1481

[[card]]
id = "IMT-01-007"
name = "デイアフターデイAMCG"
idol = "天海 春香"
rarity = "SSR"
text = "みんなと一緒なら⋯⋯どこまでもいけますっ♪"
subject = "unique"
type = "costume"
[card.appeal]
vocal = 1400
dance = 1306
visual = 1334

[[card]]
id = "IMT-01-011"
name = "ノーブルプライド"
idol = "天道 輝"
rarity = "SSR"
text = "さぁ、フェスの始まりだ！最後までついてきてくれよな！"
subject = "unique"
type = "costume"
[card.appeal]
vocal = 1333
dance = 1414
visual = 1293

# [[card]]
# id = "IMT-01-012"
# name = "ノーブルプライド"
# idol = "天道 輝"
# rarity = "SSR"
# text = "さぁ、フェスの始まりだ！最後までついてきてくれよな！"
# subject = "unique"
# type = "costume"
# [card.appeal]
# vocal = 1333
# dance = 1414
# visual = 1293

[[card]]
id = "IMT-01-015"
name = "トワイライトダンス"
idol = "最上 静香"
rarity = "SSR"
text = "黄昏の饗宴へようこそ。 魂をふるわせてあげるわ･･･！"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1209
dance = 1053
visual = 1638

[[card]]
id = "IMT-01-016"
name = "トワイライトダンス"
idol = "桜庭 薫"
rarity = "SSR"
text = "饗宴の準備は整った。宵闇が深まる迄もてなそう。"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1209
dance = 1053
visual = 1638

[[card]]
id = "IMT-01-017"
name = "ディープワイヤード"
idol = "風野 灯織"
rarity = "SSR"
text = "どうでしょう？⋯⋯似合っていますか？"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1071
dance = 1632
visual = 1122

[[card]]
id = "IMT-01-018"
name = "ディープワイヤード"
idol = "桜庭 薫"
rarity = "SSR"
text = "安心してくれ。どんな仕事も完ぺきにこなしてみせる。"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1071
dance = 1632
visual = 1122

[[card]]
id = "IMT-01-019"
name = "オリエンタルクロシズ"
idol = "本田 未央"
rarity = "R"
text = "アソビもライブも全力で！それが未央ちゃん流ってね♪"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1326
dance = 1204
visual = 1295

[[card]]
id = "IMT-01-020"
name = "オリエンタルクロシズ"
idol = "柏木 翼"
rarity = "R"
text = "わぁ、今日はなんだか楽しい日になりそうですね！"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1326
dance = 1204
visual = 1295

[[card]]
id = "IMT-01-021"
name = "ドリームナビゲーター"
idol = "渋谷 凛"
rarity = "R"
text = "私に任せといて。見たことない景色見せてあげる。"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1581
dance = 1020
visual = 1224

[[card]]
id = "IMT-01-022"
name = "ドリームナビゲーター"
idol = "柏木 翼"
rarity = "R"
text = "夢のようなフライトにようこそ。最後までお楽しみください。"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1581
dance = 1020
visual = 1224

[[card]]
id = "IMT-01-023"
name = "ミキシンググルーヴ"
idol = "櫻木 真乃"
rarity = "N"
text = "今日は思いっきり、楽しんじゃいます⋯⋯っ"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1252
dance = 1283
visual = 1240

[[card]]
id = "IMT-01-024"
name = "ミキシンググルーヴ"
idol = "天道 輝"
rarity = "N"
text = "みんなも思いっきりはじけて最高のライブにしようぜ！"
subject = "everyone"
type = "costume"
[card.appeal]
vocal = 1252
dance = 1283
visual = 1240
