[[card]]
id = "IMT-01-083"
name = "ソングオブピース"
idol = "柏木 翼"
rarity = "SSR"
text = "オレたちの歌をステージいっぱいに響かせます！"
type = "sp_appeal"
subject = "everyone"
[card.sp_appeal]
name = "ソングオブピース"
description = "成功判定のコンボ数UP(中)"

[[card]]
id = "IMT-01-084"
name = "パーティータイム"
idol = "八宮 めぐる"
rarity = "SR"
text = "みんなが笑顔になるステージわたしたちならきっとできるよ！"
type = "sp_appeal"
subject = "everyone"
[card.sp_appeal]
name = "パーティータイム"
description = "このカードを使用するとSPアピールを変更できます。"
