[[card]]
id = "IMT-01-083"
name = "ソングオブピース"
idol = "柏木 翼"
rarity = "SSR"
text = "オレたちの歌をステージいっぱいに響かせます！"
type = "sp_appeal"
subject = "everyone"
[sp_appeal]
name = "ソングオブピース"
description = "成功判定のコンボ数UP(中)" # Using first element from rhythm_live_effects as description

[[card]]
id = "IMT-01-084"
name = "パーティータイム"
idol = "八宮 めぐる"
rarity = "SR"
text = "みんなが笑顔になるステージわたしたちならきっとできるよ！"
type = "sp_appeal"
subject = "everyone"
[sp_appeal]
name = "パーティータイム"
description = "このカードを使用するとSPアピールを変更できます。" # Using first element from rhythm_live_effects as description
