[[card]]
id = "IMT-01-083"
name = "ソングオブピース"
idol = "柏木 翼"
rarity = "SSR"
text = "オレたちの歌をステージいっぱいに響かせます！"
type = "sp_appeal"
subject = "everyone"
[card.sp_appeal]
description = ["成功判定のコンボ数UP(中)"]

[[card]]
id = "IMT-01-084"
name = "パーティータイム"
idol = "八宮 めぐる"
rarity = "SR"
text = "みんなが笑顔になるステージわたしたちならきっとできるよ！"
type = "sp_appeal"
subject = "everyone"
[card.sp_appeal]
description = ["全ての判定がPERFECTになる"]

[[card]]
id = "IMT-01-085"
name = "トリオザベスト"
idol = "春日 未来"
rarity = "SR"
text = "みんなと作る最高のステージ見逃がさないでくださいね！"
type = "sp_appeal"
subject = "female"
[card.sp_appeal]
name = "パーティータイム"
description = ["GOOD以上判定時のスコアUP(小)"] 


# [[card]]
# id = "IMT-01-086"
# name = "トリオザベスト"
# idol = "春日 未来"
# rarity = "SR"
# text = "みんなと作る最高のステージ見逃がさないでくださいね！"
# type = "sp_appeal"
# subject = "female"
# [card.sp_appeal]
# name = "パーティータイム"
# description = ["GOOD以上判定時のスコアUP(小)"] 
