[[IMT-01-054]]
card_name = "all you've got"
idol_name = "渋谷 凛"
rarity = "SSR"
text = "この特別なステージで、私たちの全力を見せるよ。"
support_effects = "rhythm"
type = "support"
subject = "everyone" # Add missing subject field (assuming everyone, please verify)
