name: Deploy

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # - name: Install Nix
      #   uses: cachix/install-nix-action@v31
      #   with:
      #     github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate JSON
      #   run: nix develop --no-pure-eval --command uv run python ./generate/card_data.py

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install

      - name: Build
        run: uv run python ./generate/card_data.py

      - name: Copy pages
        run: cp ./pages/index.html ./dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: ./dist
